auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: wj1s.github.io
url: http://wj1s.github.io
feed: /atom.xml
author_info: <a href="http://wj1s.github.io/">WangJian</a>

name: Wang Jian's Blog
description: 
url: http://wj1s.github.io/